# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiWIN.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 842)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.LayoutNorth = QtWidgets.QHBoxLayout()
        self.LayoutNorth.setObjectName("LayoutNorth")
        self.Pback = QtWidgets.QPushButton(self.centralwidget)
        self.Pback.setMaximumSize(QtCore.QSize(30, 300))
        self.Pback.setObjectName("Pback")
        self.Pback.clicked.connect(self.PhotoB)
        self.LayoutNorth.addWidget(self.Pback)
        self.Photo = QtWidgets.QLabel(self.centralwidget)
        self.Photo.setMaximumSize(QtCore.QSize(400, 300))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("photo/1.jpg"))
        self.Photo.setScaledContents(True)
        self.Photo.setObjectName("Photo")
        self.LayoutNorth.addWidget(self.Photo)
        self.Pnext = QtWidgets.QPushButton(self.centralwidget)
        self.Pnext.setMaximumSize(QtCore.QSize(30, 300))
        self.Pnext.setObjectName("Pnext")
        self.Pnext.clicked.connect(self.PhotoN)
        self.LayoutNorth.addWidget(self.Pnext)
        self.Nback = QtWidgets.QPushButton(self.centralwidget)
        self.Nback.setMaximumSize(QtCore.QSize(30, 300))
        self.Nback.setObjectName("Nback")
        self.Nback.clicked.connect(self.NewsB)
        self.LayoutNorth.addWidget(self.Nback)
        self.News = QtWidgets.QTextEdit(self.centralwidget)
        self.News.setMaximumSize(QtCore.QSize(16777215, 300))
        self.News.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.News.setObjectName("News")
        self.LayoutNorth.addWidget(self.News)
        self.Nnext = QtWidgets.QPushButton(self.centralwidget)
        self.Nnext.setMaximumSize(QtCore.QSize(30, 300))
        self.Nnext.setObjectName("Nnext")
        self.Nnext.clicked.connect(self.NewsN)
        self.LayoutNorth.addWidget(self.Nnext)
        self.gridLayout.addLayout(self.LayoutNorth, 0, 0, 2, 1)
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setMaximumSize(QtCore.QSize(300, 180))
        self.Title.setText("")
        self.Title.setPixmap(QtGui.QPixmap("titL.png"))
        self.Title.setScaledContents(True)
        self.Title.setWordWrap(False)
        self.Title.setObjectName("Title")
        self.gridLayout.addWidget(self.Title, 0, 1, 1, 2)
        self.LayoutEast = QtWidgets.QGridLayout()
        self.LayoutEast.setObjectName("LayoutEast")
        self.Llogin = QtWidgets.QLabel(self.centralwidget)
        self.Llogin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Llogin.setObjectName("Llogin")
        self.LayoutEast.addWidget(self.Llogin, 1, 0, 1, 1)
        self.Login = QtWidgets.QLineEdit(self.centralwidget)
        self.Login.setMaximumSize(QtCore.QSize(200, 30))
        self.Login.setObjectName("Login")
        self.LayoutEast.addWidget(self.Login, 1, 1, 1, 1)
        self.Lpassword = QtWidgets.QLabel(self.centralwidget)
        self.Lpassword.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Lpassword.setObjectName("Lpassword")
        self.LayoutEast.addWidget(self.Lpassword, 2, 0, 1, 1)
        self.Enter = QtWidgets.QPushButton(self.centralwidget)
        self.Enter.setMaximumSize(QtCore.QSize(200, 30))
        self.Enter.setObjectName("Enter")
        self.Enter.clicked.connect(self.EnterUs)
        self.LayoutEast.addWidget(self.Enter, 3, 1, 1, 1)
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setMaximumSize(QtCore.QSize(200, 30))
        self.Password.setObjectName("Password")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LayoutEast.addWidget(self.Password, 2, 1, 1, 1)
        self.Register = QtWidgets.QPushButton(self.centralwidget)
        self.Register.setMaximumSize(QtCore.QSize(200, 30))
        self.Register.setObjectName("Register")
        self.LayoutEast.addWidget(self.Register, 4, 1, 1, 1)
        self.gridLayout.addLayout(self.LayoutEast, 1, 1, 1, 2)
        self.LayoutNorth2 = QtWidgets.QHBoxLayout()
        self.LayoutNorth2.setObjectName("LayoutNorth2")
        self.About = QtWidgets.QPushButton(self.centralwidget)
        self.About.setObjectName("About")
        self.LayoutNorth2.addWidget(self.About)
        self.Cabinet = QtWidgets.QPushButton(self.centralwidget)
        self.Cabinet.setObjectName("Cabinet")
        self.LayoutNorth2.addWidget(self.Cabinet)
        self.Rent = QtWidgets.QPushButton(self.centralwidget)
        self.Rent.setObjectName("Rent")
        self.LayoutNorth2.addWidget(self.Rent)
        self.Services = QtWidgets.QPushButton(self.centralwidget)
        self.Services.setObjectName("Services")
        self.LayoutNorth2.addWidget(self.Services)
        self.Contacts = QtWidgets.QPushButton(self.centralwidget)
        self.Contacts.setObjectName("Contacts")
        self.LayoutNorth2.addWidget(self.Contacts)
        self.Manual = QtWidgets.QPushButton(self.centralwidget)
        self.Manual.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Manual.setObjectName("Manual")
        self.LayoutNorth2.addWidget(self.Manual)
        self.gridLayout.addLayout(self.LayoutNorth2, 2, 0, 1, 1)
        self.Comment = QtWidgets.QPushButton(self.centralwidget)
        self.Comment.setMaximumSize(QtCore.QSize(300, 16777215))
        self.Comment.setObjectName("Comment")
        self.gridLayout.addWidget(self.Comment, 2, 1, 1, 1)
        self.exitB = QtWidgets.QPushButton(self.centralwidget)
        self.exitB.setObjectName("exitB")
        self.exitB.clicked.connect(exit)
        self.gridLayout.addWidget(self.exitB, 2, 2, 1, 1)
        self.Text = QtWidgets.QTextEdit(self.centralwidget)
        self.Text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Text.setObjectName("Text")
        self.gridLayout.addWidget(self.Text, 3, 0, 1, 1)
        self.tableC = QtWidgets.QTableView(self.centralwidget)
        self.tableC.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableC.setObjectName("tableC")
        self.gridLayout.addWidget(self.tableC, 3, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1166, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Pback.setText(_translate("MainWindow", "<"))
        self.Pnext.setText(_translate("MainWindow", ">"))
        self.Nback.setText(_translate("MainWindow", "<"))
        self.Nnext.setText(_translate("MainWindow", ">"))
        self.Llogin.setText(_translate("MainWindow", "Логин"))
        self.Lpassword.setText(_translate("MainWindow", "Пароль"))
        self.Enter.setText(_translate("MainWindow", "Вход"))
        self.Register.setText(_translate("MainWindow", "Регистрация"))
        self.About.setText(_translate("MainWindow", "О Нас"))
        self.Cabinet.setText(_translate("MainWindow", "Помещение"))
        self.Rent.setText(_translate("MainWindow", "Аренда"))
        self.Services.setText(_translate("MainWindow", "Услуги"))
        self.Contacts.setText(_translate("MainWindow", "Контакты"))
        self.Manual.setText(_translate("MainWindow", "Инструкция"))
        self.Comment.setText(_translate("MainWindow", "Оставить отзыв"))
        self.exitB.setText(_translate("MainWindow", "Закрыть программу"))

