# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Priv.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormPriv(object):
    def setupUi(self, FormPriv):
        FormPriv.setObjectName("FormPriv")
        FormPriv.resize(1173, 708)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 180, 180))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        FormPriv.setPalette(palette)
        self.gridLayout_4 = QtWidgets.QGridLayout(FormPriv)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Login = QtWidgets.QLabel(FormPriv)
        self.Login.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Login.setObjectName("Login")
        self.gridLayout.addWidget(self.Login, 1, 1, 1, 1)
        self.Status = QtWidgets.QLabel(FormPriv)
        self.Status.setMaximumSize(QtCore.QSize(150, 16777215))
        self.Status.setObjectName("Status")
        self.gridLayout.addWidget(self.Status, 2, 1, 1, 1)
        self.statusL = QtWidgets.QLabel(FormPriv)
        self.statusL.setMaximumSize(QtCore.QSize(150, 16777215))
        self.statusL.setObjectName("statusL")
        self.gridLayout.addWidget(self.statusL, 2, 0, 1, 1)
        self.LoginL = QtWidgets.QLabel(FormPriv)
        self.LoginL.setMaximumSize(QtCore.QSize(150, 16777215))
        self.LoginL.setObjectName("LoginL")
        self.gridLayout.addWidget(self.LoginL, 1, 0, 1, 1)
        self.DateL = QtWidgets.QLabel(FormPriv)
        self.DateL.setObjectName("DateL")
        self.gridLayout.addWidget(self.DateL, 3, 0, 1, 1)
        self.TimeL = QtWidgets.QLabel(FormPriv)
        self.TimeL.setObjectName("TimeL")
        self.gridLayout.addWidget(self.TimeL, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Exit = QtWidgets.QPushButton(FormPriv)
        self.Exit.setObjectName("Exit")
        self.gridLayout_2.addWidget(self.Exit, 0, 6, 1, 1)
        self.NewsAdminB = QtWidgets.QPushButton(FormPriv)
        self.NewsAdminB.setObjectName("NewsAdminB")
        self.gridLayout_2.addWidget(self.NewsAdminB, 0, 2, 1, 1)
        self.Comment = QtWidgets.QPushButton(FormPriv)
        self.Comment.setObjectName("Comment")
        self.gridLayout_2.addWidget(self.Comment, 0, 1, 1, 1)
        self.newPhoto = QtWidgets.QPushButton(FormPriv)
        self.newPhoto.setObjectName("newPhoto")
        self.gridLayout_2.addWidget(self.newPhoto, 0, 4, 1, 1)
        self.deleteB = QtWidgets.QPushButton(FormPriv)
        self.deleteB.setEnabled(True)
        self.deleteB.setAutoDefault(False)
        self.deleteB.setDefault(False)
        self.deleteB.setFlat(False)
        self.deleteB.setObjectName("deleteB")
        self.gridLayout_2.addWidget(self.deleteB, 3, 2, 1, 1)
        self.addB = QtWidgets.QPushButton(FormPriv)
        self.addB.setObjectName("addB")
        self.gridLayout_2.addWidget(self.addB, 3, 1, 1, 1)
        self.PayB = QtWidgets.QPushButton(FormPriv)
        self.PayB.setObjectName("PayB")
        self.gridLayout_2.addWidget(self.PayB, 1, 2, 1, 1)
        self.RecordB = QtWidgets.QPushButton(FormPriv)
        self.RecordB.setObjectName("RecordB")
        self.gridLayout_2.addWidget(self.RecordB, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.Table = QtWidgets.QTableView(FormPriv)
        self.Table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.Table.setObjectName("Table")
        self.gridLayout_4.addWidget(self.Table, 2, 1, 4, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DayT = QtWidgets.QTextEdit(FormPriv)
        self.DayT.setMinimumSize(QtCore.QSize(150, 150))
        self.DayT.setMaximumSize(QtCore.QSize(400, 150))
        self.DayT.setObjectName("DayT")
        self.gridLayout_3.addWidget(self.DayT, 0, 0, 1, 1)
        self.DayB = QtWidgets.QPushButton(FormPriv)
        self.DayB.setObjectName("DayB")
        self.gridLayout_3.addWidget(self.DayB, 1, 0, 1, 1)
        self.TabSea = QtWidgets.QGroupBox(FormPriv)
        self.TabSea.setObjectName("TabSea")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.TabSea)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.PayDate = QtWidgets.QDateEdit(self.TabSea)
        self.PayDate.setObjectName("PayDate")
        self.gridLayout_5.addWidget(self.PayDate, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.TabSea)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 3, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.TabSea)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 2)
        self.RecDate = QtWidgets.QDateEdit(self.TabSea)
        self.RecDate.setObjectName("RecDate")
        self.gridLayout_5.addWidget(self.RecDate, 1, 0, 1, 1)
        self.BandBox = QtWidgets.QComboBox(self.TabSea)
        self.BandBox.setObjectName("BandBox")
        self.gridLayout_5.addWidget(self.BandBox, 7, 0, 1, 1)
        self.EnterRecB = QtWidgets.QPushButton(self.TabSea)
        self.EnterRecB.setObjectName("EnterRecB")
        self.gridLayout_5.addWidget(self.EnterRecB, 7, 1, 1, 1)
        self.EnterPayB = QtWidgets.QPushButton(self.TabSea)
        self.EnterPayB.setObjectName("EnterPayB")
        self.gridLayout_5.addWidget(self.EnterPayB, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.TabSea)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 6, 0, 1, 2)
        self.EnterPay = QtWidgets.QPushButton(self.TabSea)
        self.EnterPay.setObjectName("EnterPay")
        self.gridLayout_5.addWidget(self.EnterPay, 4, 1, 1, 1)
        self.EnterRec = QtWidgets.QPushButton(self.TabSea)
        self.EnterRec.setObjectName("EnterRec")
        self.gridLayout_5.addWidget(self.EnterRec, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.TabSea, 0, 1, 2, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 6, 0, 1, 2)
        self.Box = QtWidgets.QComboBox(FormPriv)
        self.Box.setEditable(False)
        self.Box.setMinimumContentsLength(0)
        self.Box.setDuplicatesEnabled(False)
        self.Box.setObjectName("Box")
        self.gridLayout_4.addWidget(self.Box, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(FormPriv)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.ReportBox = QtWidgets.QGroupBox(FormPriv)
        self.ReportBox.setObjectName("ReportBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ReportBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.yearB = QtWidgets.QPushButton(self.ReportBox)
        self.yearB.setObjectName("yearB")
        self.verticalLayout.addWidget(self.yearB)
        self.mountB = QtWidgets.QPushButton(self.ReportBox)
        self.mountB.setObjectName("mountB")
        self.verticalLayout.addWidget(self.mountB)
        self.gridLayout_4.addWidget(self.ReportBox, 4, 0, 2, 1)

        self.retranslateUi(FormPriv)
        QtCore.QMetaObject.connectSlotsByName(FormPriv)

    def retranslateUi(self, FormPriv):
        _translate = QtCore.QCoreApplication.translate
        FormPriv.setWindowTitle(_translate("FormPriv", "Привилегированный режим"))
        self.Login.setText(_translate("FormPriv", "Гость"))
        self.Status.setText(_translate("FormPriv", "Гость"))
        self.statusL.setText(_translate("FormPriv", "Статус -"))
        self.LoginL.setText(_translate("FormPriv", "Логин -"))
        self.DateL.setText(_translate("FormPriv", "24 Июня 2017"))
        self.TimeL.setText(_translate("FormPriv", "12 : 25"))
        self.Exit.setText(_translate("FormPriv", "Выход"))
        self.NewsAdminB.setText(_translate("FormPriv", "Добавить Новость"))
        self.Comment.setText(_translate("FormPriv", "Оставить отзыв"))
        self.newPhoto.setText(_translate("FormPriv", "Добавить Фото"))
        self.deleteB.setText(_translate("FormPriv", "Удалить"))
        self.addB.setText(_translate("FormPriv", "Добавить"))
        self.PayB.setText(_translate("FormPriv", "Прием Оплаты"))
        self.RecordB.setText(_translate("FormPriv", "Записать"))
        self.DayB.setText(_translate("FormPriv", "Вывести в таблицу"))
        self.TabSea.setTitle(_translate("FormPriv", "Поиск в Таблицах"))
        self.label_2.setText(_translate("FormPriv", "Вывести акты приема оплаты по дате:"))
        self.label.setText(_translate("FormPriv", "Вывести записи по дате:"))
        self.EnterRecB.setText(_translate("FormPriv", "Вывести Записи"))
        self.EnterPayB.setText(_translate("FormPriv", "Вывести Акты приема."))
        self.label_4.setText(_translate("FormPriv", "Вывести данные о группе:"))
        self.EnterPay.setText(_translate("FormPriv", "Вывести"))
        self.EnterRec.setText(_translate("FormPriv", "Вывести"))
        self.label_3.setText(_translate("FormPriv", "Таблицы "))
        self.ReportBox.setTitle(_translate("FormPriv", "Отчеты"))
        self.yearB.setText(_translate("FormPriv", "За Год"))
        self.mountB.setText(_translate("FormPriv", "За Месяц"))

